default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("LISTFY_DATABASE_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("LISTFY_DATABASE_PASSWORD") { 'postgres' } %>
  host: <%= ENV.fetch("LISTFY_DATABASE_HOST") { 'localhost' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: listify_dev

test:
  <<: *default
  database: listify_test

production:
  <<: *default
  database: listify_prod
  username: <%= ENV.fetch("LISTFY_DATABASE_USERNAME") { 'postgres' } %>
  password: <%= ENV['LISTFY_DATABASE_PASSWORD'] %>
