default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 1234
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: listfy_dev

test:
  <<: *default
  database: listfy_test

production:
  <<: *default
  database: listfy_prod
  username: postres
  password: <%= ENV['LISTFY_DATABASE_PASSWORD'] %>
